CREATE TABLE IF NOT EXISTS zk_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  license VARCHAR(64) NOT NULL UNIQUE,
  discord_id VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS zk_characters (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  first_name VARCHAR(32) NOT NULL,
  last_name VARCHAR(32) NOT NULL,
  dob DATE NULL,
  last_position JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_zk_characters_user_id FOREIGN KEY (user_id) REFERENCES zk_users(id)
);

CREATE TABLE IF NOT EXISTS zk_schema_migrations (
  name VARCHAR(128) NOT NULL UNIQUE,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
