CREATE TABLE IF NOT EXISTS zk_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  license VARCHAR(64) NOT NULL UNIQUE,
  discord_id VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
